//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace real_estate_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public string ListingID { get; set; }
        public string Type { get; set; }
        public string Number { get; set; }
        public string DisplayOrder { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> Created_TMS { get; set; }
        public Nullable<System.DateTime> Modified_TMS { get; set; }
        public string URLThumb { get; set; }
        public System.Guid ID { get; set; }
    }
}
