//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace real_estate_app.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MLSEntities : DbContext
    {
        public MLSEntities()
            : base("name=MLSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AllProperty> AllProperties { get; set; }
        public DbSet<Medium> Media { get; set; }
        public DbSet<StateCountyCity> StateCountyCities { get; set; }
        public DbSet<StateCountyTownship> StateCountyTownships { get; set; }
        public DbSet<StateSchoolDistrict> StateSchoolDistricts { get; set; }
    }
}
