//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace real_estate_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateCountyTownship
    {
        public string State { get; set; }
        public string County { get; set; }
        public string Township { get; set; }
        public System.Guid ID { get; set; }
    }
}
